[package]
name = "zig_build"
edition = "2018"
publish = false
version = "0.5.0"

[dependencies]
xz2 = "0.1.6"
flate2 = "1.0.13"
tar = "0.4.26"

[target.'cfg(unix)'.dependencies]
zig_build_linux_x86_64 = { path = "../zig_build_linux_x86_64" }
